***Задание 1***

Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).


In [4]:
import numpy as np

In [137]:
N = 10
x = np.arange( 0, N )

In [138]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

***Задание 2***

Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [62]:
diag_matrix_begin = -4
diag_matrix_end = 0

In [63]:
diag_matrix = np.diag(np.arange(diag_matrix_begin,diag_matrix_end), k=0)
diag_matrix

array([[-4,  0,  0,  0],
       [ 0, -3,  0,  0],
       [ 0,  0, -2,  0],
       [ 0,  0,  0, -1]])

In [64]:
diag_sum = 0
for i in range(len(diag_matrix[0])):
    diag_sum += diag_matrix[i][i]
diag_sum  

-10

***Задание 3***


Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. Определите какому фильму было выставлено больше всего оценок 5.0.


In [94]:
import pandas as pd

In [98]:
movies = pd.read_csv('C:/Users/anton/Documents/NETOLOGY/Courses/Python/Homework/ml-latest-small/movies.csv')
ratings = pd.read_csv('C:/Users/anton/Documents/NETOLOGY/Courses/Python/Homework/ml-latest-small/ratings.csv')

In [134]:
joined = ratings.merge(movies, on='movieId', how='left')

In [135]:
data = joined[ joined.rating == 5.0]
data_movies_grouped = data.groupby('movieId')

In [136]:
data[['movieId', 'rating']].groupby('movieId').count().sort_values('rating', ascending=False).head(1)

rating
movieId        
318         153

***Задание 4***

По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity.

In [240]:
import pandas as pd
data_power = pd.read_csv('C:/Users/anton/Documents/NETOLOGY/Courses/Python/5/power.csv')

In [255]:
filtered_data_power = data_power[ 
                                (
                                (data_power.category == 4) | 
                                (data_power.category == 12) | 
                                (data_power.category == 21)
                                ) & (
                                (data_power['country'] =='Lithuania') |  
                                (data_power['country'] =='Estonia') | 
                                (data_power['country'] =='Latvia') 
                                ) & ( 
                                (data_power ['quantity'] >0)
                                ) & (
                                (data_power['year'] > 2005) | 
                                (2010 > data_power['year']) 
                                )
                                ]

filtered_data_power.head()

country  year  quantity  category
10617  Estonia  2008       1.0         4
10620  Estonia  2005       1.0         4
10621  Estonia  2004       1.0         4
10622  Estonia  2003       1.0         4
10624  Estonia  2001       1.0         4

In [258]:
filtered_data_power[['quantity']].sum()

quantity    970728.0
dtype: float64

***Задание 5***

Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [262]:
import numpy as np
from numpy import linalg

In [263]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )

In [264]:
b = np.array( [4, 12, -3] )

In [265]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [266]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True